name: Generate Site

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 7,19 * * *"

jobs:
  generate-site:
    name: Generate Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install gnuplot
      run: sudo apt-get -y install libsm6 libice6 gnuplot

    - name: Install gems
      run: bundle install

    - name: Build site
      run: bundle exec generate-site

    - name: Configure git
      run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com" &&
           git config user.name "$GITHUB_ACTOR" &&
           git fetch

    - name: Commit generated site
      run: mv public temp &&
           git checkout published-site &&
           mv -f temp/* public/ &&
           git add public &&
           git commit -m "Build site ($(date))"

    - name: Push to published-site branch ready for Heroku to deploy
      run: git push --set-upstream origin HEAD:published-site
